from mainCode import *


#region #after 2018

# listIndex =  ['', '', 2, '', 4, '', 6, '', 8, '', 10, '', '', '', 14, '', 16, '', 18, 19]
# listTitle =  ['', '', "Does audit report information improve financial distress prediction over Altman's traditional Z‐Score model?", '', 'The effects of financial distress: Evidence from US GDP growth', '', 'Corporate social responsibility performance, financial distress and firm life cycle: evidence from Australia', '', 'A three-stage dynamic model of financial distress', '', 'Losing public health insurance: TennCare reform and personal financial distress', '', '', '', 'Incorporating textual and management factors into financial distress prediction: A comparative study of machine learning methods', '', 'CUS-heterogeneous ensemble-based financial distress prediction for imbalanced dataset with ensemble feature selection', '', 'Investigating operational predictors of future financial distress in the US airline industry', 'European country heterogeneity in financial distress prediction: An empirical analysis with macroeconomic and regulatory factors']
# listLink =  ['', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/jifm.12110', '', 'https://www.sciencedirect.com/science/article/pii/S0264999317315791', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/acfi.12277', '', 'https://www.emerald.com/insight/content/doi/10.1108/mf-07-2017-0244/full/html', '', 'https://www.sciencedirect.com/science/article/pii/S0047272720300669', '', '', '', 
# 'https://onlinelibrary.wiley.com/doi/abs/10.1002/for.2661', '', 'https://www.sciencedirect.com/science/article/pii/S1568494620306967', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/poms.12829', 'https://www.sciencedirect.com/science/article/pii/S0264999319304493']
# listSnippet =  ['', '', "We analyze empirically the usefulness of combining accounting and auditing data in order to predict corporate financial distress. Concretely, we examine whether audit report information incrementally predicts distress over a traditional accounting model: the Altman's Z‐Score …", '', 'This study provides a dynamic characterization of the link between financial distress risk and the real economy. Using a large dataset of firm-level observations, new ex-ante measures of financial distress are developed at the sector level and used to examine growth trends in the …', '', "This study examines the association between corporate social responsibility (CSR) performance and financial distress and additionally the moderating impact of firm life cycle stages on that association. Based on a sample of 651 publicly listed Australian firm‐years' …", '', 'Purpose The purpose of this paper is to explain the multi-stage dynamic process of financial distress. An attempt is made to explore multiple adverse heterogeneous events of financial distress leading a firm closer to bankruptcy progressively. Design/methodology/approach …', '', 'A primary goal of health insurance is smoothing the financial risk associated with health shocks. We estimate the effect of exposure to health-insurance reform on individual-level financial well-being. Utilizing a plausibly exogenous shock to health insurance status …', '', '', '', 'Financial distress prediction (FDP) has been widely considered as a promising approach to reducing financial losses. While financial information comprises the traditional factors involved in FDP, nonfinancial factors have also been examined in recent studies. In light of …', '', "Due to the global financial crisis occurred in 2008, with a large amount of companies troubling in financial distress, the machine learning-based prediction of this dilemma has shown economic stakeholders' great practicability. In the field of machine learning, most of …", '', 'We investigate the predictive power of operational performance on future financial distress in the context of the US airline industry. We focus on four areas of operational performance: revenue management, operational efficiency, service quality, and operational complexity …', 'This study tried to improve the understanding of the impact of context variables on the risk of financial difficulties from an European companies experience. To this end, a multilevel logistic model is developed to exploit the benefits of transnational analysis and to examine …']
# listCitedBy =  ['', '', 19, '', 23, '', 105, '', 18, '', 34, '', '', '', 11, '', 9, '', 16, 8]

# listIndex = ['', '', '', '', '', '', '', 7, '', '', '', '', '', '', 14, '', '', '', '', '']
# listTitle = ['', '', '', '', '', '', '', 'Does compliance with corporate governance codes help to mitigate financial distress?', '', '', '', '', '', '', 'Leadership change and corporate social performance: The context of financial distress makes all the difference', '', '', '', '', '']
# listLink = ['', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S0275531920309521', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1048984318303412', '', '', '', '', '']
# listSnippet = ['', '', '', '', '', '', '', '… corporate governance on the likelihood of financial distress. Our results highlight that the likelihood of financial distress is only reduced when the … Corporate reputation and corporate social responsibility practices are expected to be correlated with the CGC compliance since the …', '', '', '', '', '', '', '… Each of these dimensions has a strengths score (socially responsible behavior) and a concern score (socially irresponsible behavior). Empirical research has demonstrated that the strengths and concerns scores represent separate constructs (Strike, Gao, & Bansal, 2006) due …', '', '', '', '', '']
# listCitedBy = ['', '', '', '', '', '', '', 5, '', '', '', '', '', '', 10, '', '', '', '', '']

# link https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=13&num=21&as_ylo=2018
# listIndex = ['', '', '', '', '', '', '', 7, '', '', '', '', '', '', 14, '', '', '', '', '']
# listTitle = ['', '', '', '', '', '', '', 'Does compliance with corporate governance codes help to mitigate financial distress?', '', '', '', '', '', '', 'Leadership change and corporate social performance: The context of financial distress makes all the difference', '', '', '', '', '']
# listLink = ['', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S0275531920309521', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1048984318303412', '', '', '', '', '']
# listSnippet = ['', '', '', '', '', '', '', '… corporate governance on the likelihood of financial distress. Our results highlight that the likelihood of financial distress is only reduced when the … Corporate reputation and corporate social responsibility practices are expected to be correlated with the CGC compliance since the …', '', '', '', '', '', '', '… Each of these dimensions has a strengths score (socially responsible behavior) and a concern score (socially irresponsible behavior). Empirical research has demonstrated that the strengths and concerns scores represent separate constructs (Strike, Gao, & Bansal, 2006) due …', '', '', '', '', '']
# listSummary = ['', '', '', '', '', '', '', 'F Bravo-Urquiza, E Moreno-Ureba - … in International Business and Finance, 2021 - Elsevier', '', '', '', '', '', '', 'SCS Chiu, JL Walls - The Leadership Quarterly, 2019 - Elsevier', '', '', '', '', '']
# listCitedBy = ['', '', '', '', '', '', '', 5, '', '', '', '', '', '', 10, '', '', '', '', '']
# listSource = ['', '', '', '', '', '', '', 'sciencedirect', '', '', '', '', '', '', 'sciencedirect', '', '', '', '', '']

# https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=20&num=21&as_ylo=2018
# listIndex = ['', 1, '', '', '', '', '', '', 8, '', '', '', '', '', '', '', '', '', '', '']
# listTitle = ['', 'Does compliance with corporate governance codes help to mitigate financial distress?', '', '', '', '', '', '', 'Leadership change and corporate social performance: The context of financial distress makes all the difference', '', '', '', '', '', '', '', '', '', '', '']
# listLink = ['', 'https://www.sciencedirect.com/science/article/pii/S0275531920309521', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1048984318303412', '', '', '', '', '', '', '', '', '', '', '']
# listSnippet = ['', '… corporate governance on the likelihood of financial distress. Our results highlight that the likelihood of financial distress is only reduced when the … Corporate reputation and corporate social responsibility practices are expected to be correlated with the CGC compliance since the …', '', '', '', '', '', '', '… Each of these dimensions has a strengths score (socially responsible behavior) and a concern score (socially irresponsible behavior). Empirical research has demonstrated that the strengths and concerns scores represent separate constructs (Strike, Gao, & Bansal, 2006) due …', '', '', '', '', '', '', '', '', '', '', '']
# listSummary = ['', 'F Bravo-Urquiza, E Moreno-Ureba - … in International Business and Finance, 2021 - Elsevier', '', '', '', '', '', '', 'SCS Chiu, JL Walls - The Leadership Quarterly, 2019 - Elsevier', '', '', '', '', '', '', '', '', '', '', '']
# listCitedBy = ['', 5, '', '', '', '', '', '', 10, '', '', '', '', '', '', '', '', '', '', '']
# listSource = ['', 'sciencedirect', '', '', '', '', '', '', 'sciencedirect', '', '', '', '', '', '', '', '', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=30&num=21&as_ylo=2018'
# listIndex = ['', '', '', '', '', '', '', '', '', '', '', '', 12, '', '', '', '', '', '', '']
# listTitle = ['', '', '', '', '', '', '', '', '', '', '', '', 'The effect of corporate governance structure on financial difficulties', '', '', '', '', '', '', '']
# listLink = ['', '', '', '', '', '', '', '', '', '', '', '', 'https://search.proquest.com/openview/a822ecb8d63866362ffad40a7a3d1d3b/1?pq-origsite=gscholar&cbl=4916366', '', '', '', '', '', '', '']
# listSnippet = ['', '', '', '', '', '', '', '', '', '', '', '', '… So it can be concluded that the contribution of CG through the proxy committee audit (KA) and independent commissioners (KI) and CSR to the magnitude of the value of financial distress (FD) is only around 7.6% while the rest is explained by other variables. …', '', '', '', '', '', '', '']
# listSummary = ['', '', '', '', '', '', '', '', '', '', '', '', 'W Andayani, D Daud - Entrepreneurship and Sustainability …, 2020 - search.proquest.com', '', '', '', '', '', '', '']
# listCitedBy = ['', '', '', '', '', '', '', '', '', '', '', '', 3, '', '', '', '', '', '', '']
# listSource = ['', '', '', '', '', '', '', '', '', '', '', '', 'proquest', '', '', '', '', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=40&num=21&as_ylo=2018'
# listIndex = ['', '', '', 3, '', '', '', '', '', '', '', '', 12, '', '', '', '', '', '', '']
# listTitle = ['', '', '', 'The effect of corporate governance structure on financial difficulties', '', '', '', '', '', '', '', '', 'On the prediction of financial distress in emerging markets: What matters more? Empirical evidence from Arab spring countries', '', '', '', '', '', '', '']
# listLink = ['', '', '', 'https://search.proquest.com/openview/a822ecb8d63866362ffad40a7a3d1d3b/1?pq-origsite=gscholar&cbl=4916366', '', '', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1566014121000145', '', '', '', '', '', '', '']
# listSnippet = ['', '', '', '… So it can be concluded that the contribution of CG through the proxy committee audit (KA) and independent commissioners (KI) and CSR to the magnitude of the value of financial distress (FD) is only around 7.6% while the rest is explained by other variables. …', '', '', '', '', '', '', '', '', '… However, this study examines the determinants of firm financial distress, while controlling for the Arab Spring, institutional variables, … financial distress in a cross-country analysis of financial distress, and examine the effect of firm maturity as a proxy for firm life on financial distress…', '', '', '', '', '', '', '']
# listSummary = ['', '', '', 'W Andayani, D Daud - Entrepreneurship and Sustainability …, 2020 - search.proquest.com', '', '', '', '', '', '', '', '', 'MA ElBannan - Emerging Markets Review, 2021 - Elsevier', '', '', '', '', '', '', '']
# listCitedBy = ['', '', '', 3, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
# listSource = ['', '', '', 'proquest', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=50&num=21&as_ylo=2018'
# listIndex = [0, '', '', '', '', '', '', '', '', '', '', 11, '', '', '', 15, 16, '', '', '']
# listTitle = ['On the prediction of financial distress in emerging markets: What matters more? Empirical evidence from Arab spring countries', '', '', '', '', '', '', '', '', '', '', 'Corporate social responsibility engagement of financially distressed firms and their bankruptcy likelihood', '', '', '', 'Does corporate social responsibility help the survivorship of SMEs and large firms?', 'Does managerial ownership influence corporate social responsibility (CSR)? The role of economic policy uncertainty', '', '', '']
# listLink = ['https://www.sciencedirect.com/science/article/pii/S1566014121000145', '', '', '', '', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S0882611018300981', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1044028317304106', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/acfi.12592', '', '', '']
# listSnippet = ['… However, this study examines the determinants of firm financial distress, while controlling for the Arab Spring, institutional variables, … financial distress in a cross-country analysis of financial distress, and examine the effect of firm maturity as a proxy for firm life on financial distress…', '', '', '', '', '', '', '', '', '', '', '… This study aims to evaluate the value of corporate social responsibility (CSR, henceforth) in the context of corporate financial distress. At the crux of the study is a simple question: whether and how the bankruptcy likelihood of financially distressed firms can be reduced by their …', '', '', '', "… To test the prediction that CSR activism is valuable for reducing a firm's risk of financial distress, we begin by collecting data on … firms highlights the need to properly consider selection bias concerns when we analyze the impact of CSR on a firm's risk of financial distress. …", '… To explore the drivers of corporate social responsibility (CSR), we investigate how managerial ownership influences CSR in the presence … of CSR on financial distress is significantly stronger for mature companies. Tran and O’Sullivan (2019) report that firms with stronger CSR …', '', '', '']
# listSummary = ['MA ElBannan - Emerging Markets Review, 2021 - Elsevier', '', '', '', '', '', '', '', '', '', '', 'KC Lin, X Dong - Advances in accounting, 2018 - Elsevier', '', '', '', 'F Gangi, A Meles, S Monferrà, M Mustilli - Global Finance Journal, 2020 - Elsevier', 'V Ongsakul, P Jiraporn… - … & Finance, 2021 - Wiley Online Library', '', '', '']
# listCitedBy = ['', '', '', '', '', '', '', '', '', '', '', 23, '', '', '', 34, 10, '', '', '']
# listSource = ['', '', '', '', '', '', '', '', '', '', '', 'sciencedirect', '', '', '', 'sciencedirect', 'wiley', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=60&num=21&as_ylo=2018'
# listIndex = ['', 1, '', '', '', 5, 6, '', '', '', '', '', '', '', '', '', '', '', '', 19]
# listTitle = ['', 'Corporate social responsibility engagement of financially distressed firms and their bankruptcy likelihood', '', '', '', 'Does corporate social responsibility help the survivorship of SMEs and large firms?', 'Does managerial ownership influence corporate social responsibility (CSR)? The role of economic policy uncertainty', '', '', '', '', '', '', '', '', '', '', '', '', "US quantitative easing and firm's default risk: The role of Corporate Social Responsibility (CSR)"]
# listLink = ['', 'https://www.sciencedirect.com/science/article/pii/S0882611018300981', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1044028317304106', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/acfi.12592', '', '', '', '', '', '', '', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1062976921000727']
# listSnippet = ['', '… This study aims to evaluate the value of corporate social responsibility (CSR, henceforth) in the context of corporate financial distress. At the crux of the study is a simple question: whether and how the bankruptcy likelihood of financially distressed firms can be reduced by their …', '', '', '', "… To test the prediction that CSR activism is valuable for reducing a firm's risk of financial distress, we begin by collecting data on … firms highlights the need to properly consider selection bias concerns when we analyze the impact of CSR on a firm's risk of financial distress. …", '… To explore the drivers of corporate social responsibility (CSR), we investigate how managerial ownership influences CSR in the presence … of CSR on financial distress is significantly stronger for mature companies. Tran and O’Sullivan (2019) report that firms with stronger CSR …', '', '', '', '', '', '', '', '', '', '', '', '', '… CSR performance activity is a significant determinant of financial distress, we hypothesize that excellent CSR performance is associated with reduced distress, whereas an average CSR … QE policies and financial distress risk by investigating whether CSR performance reduces a …']
# listSummary = ['', 'KC Lin, X Dong - Advances in accounting, 2018 - Elsevier', '', '', '', 'F Gangi, A Meles, S Monferrà, M Mustilli - Global Finance Journal, 2020 - Elsevier', 'V Ongsakul, P Jiraporn… - … & Finance, 2021 - Wiley Online Library', '', '', '', '', '', '', '', '', '', '', '', '', 'FJ Hsu, SH Chen - The Quarterly Review of Economics and Finance, 2021 - Elsevier']
# listCitedBy = ['', 23, '', '', '', 34, 10, '', '', '', '', '', '', '', '', '', '', '', '', 2]
# listSource = ['', 'sciencedirect', '', '', '', 'sciencedirect', 'wiley', '', '', '', '', '', '', '', '', '', '', '', '', 'sciencedirect']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=80&num=21&as_ylo=2018'
# listIndex = ['', '', 2, '', 4, '', 6, '', '', '', 10, '', '', '', '', '', 16, '', '', '']
# listTitle = ['', '', "US quantitative easing and firm's default risk: The role of Corporate Social Responsibility (CSR)", '', 'An ethical perspective of business CSR and the COVID-19 pandemic', '', 'Religiosity and financial distress in US firms', '', '', '', 'The relationship between corporate social responsibility and sustainable financial performance: Firm‐level evidence from Taiwan', '', '', '', '', '', "Does the efficiency of corporate governance and intellectual capital affect a firm's financial distress? Evidence from Egypt", '', '', '']
# listLink = ['', '', 'https://www.sciencedirect.com/science/article/pii/S1062976921000727', '', 'https://www.emerald.com/insight/content/doi/10.1108/SBR-06-2020-0086/full/html', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/ijfe.1994', '', '', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/csr.1647', '', '', '', '', '', 'https://www.emerald.com/insight/content/doi/10.1108/JIC-06-2019-0143/full/html', '', '', '']
# listSnippet = ['', '', '… CSR performance activity is a significant determinant of financial distress, we hypothesize that excellent CSR performance is associated with reduced distress, whereas an average CSR … QE policies and financial distress risk by investigating whether CSR performance reduces a …', '', '… Businesses have seen increased demand for corporate social responsibility (CSR) activities in response to the pandemic. We discuss the change in the value of CSR and the types of CSR that are now important. We review business actions taken in response to the pandemic in …', '', '… She engages in putting pressure on the firms to be more socially responsible. The General Electric executive said that for many years many people avoid meeting … Specifically, we examine whether religious social norms have an impact on financial distress in the United States. …', '', '', '', '… between corporate social responsibility (CSR) and corporate financial performance (CFP) in Taiwan. … CSR awards as a social responsibility indicator, this study finds that socially responsible firms can achieve financial results superior to those of firms which do not pursue CSR …', '', '', '', '', '', '… In the framework of seeking to build such an early warning system for financial distress, recent studies related to financial distress also suggest that CG mechanisms and IC could have a significant impact on the likelihood of a firm’s financial distress (Cardoso …', '', '', '']
# listSummary = ['', '', 'FJ Hsu, SH Chen - The Quarterly Review of Economics and Finance, 2021 - Elsevier', '', 'T Manuel, TL Herron - Society and Business Review, 2020 - emerald.com', '', 'I Gharbi, M Hamed‐Sidhom… - … Journal of Finance & …, 2021 - Wiley Online Library', '', '', '', 'TCT Hou - Corporate Social Responsibility and Environmental …, 2019 - Wiley Online Library', '', '', '', '', '', 'TM Shahwan, AM Habib - Journal of Intellectual Capital, 2020 - emerald.com', '', '', '']
# listCitedBy = ['', '', 2, '', 52, '', 1, '', '', '', 122, '', '', '', '', '', 22, '', '', '']
# listSource = ['', '', 'sciencedirect', '', 'emerald', '', 'wiley', '', '', '', 'wiley', '', '', '', '', '', 'emerald', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=100&num=21&as_ylo=2018'
# listIndex = ['', '', '', '', 4, '', '', '', 8, 9, '', '', '', '', 14, '', '', '', 18, '']
# listTitle = ['', '', '', '', 'DEPENDENCY ON CORPORATE INVESTMENT MANAGEMENT IN THE CONTEXT OF FINANCIAL DISTRESS AND CONSTRAINT', '', '', '', 'Does positive CSR increase willingness to invest in a company based on performance? The incremental role of combined assurance', 'Financial Information Asymmetry: Using Deep Learning Algorithms to Predict Financial Distress. Symmetry 2021, 13, 443', '', '', '', '', 'Imitative innovation and financial distress risk: The moderating role of executive foreign experience', '', '', '', 'Corporate social responsibility and default risk: International evidence', '']
# listLink = ['', '', '', '', 'https://search.proquest.com/openview/bbe77a929d8ee836ed8cefaebf670751/1?pq-origsite=gscholar&cbl=5003933', '', '', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/acfi.12771', 'https://search.proquest.com/openview/48cacdfe1e37e05123d30e8f90f204b6/1?pq-origsite=gscholar&cbl=2032326', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1059056020302239', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S1544612321001446', '']
# listSnippet = ['', '', '', '', '… The independent variables in this study are financial distress (X1) and financial constraint (X2). Financial distress is measured using the Altman Z-Score, where companies with a Z-Score below 1.23 are sampled in this study, the Z-Score calculation follows the following formula: …', '', '', '', '… CSR assurance is communicated, can add incremental value to the reliability of CSR information and increase investors’ decisions to invest in a company that has negative financial … Taylor, and MM Hasan, 2017, Corporate social responsibility performance, financial distress …', '… and society; hence, it is very important to build high-accuracy financial distress prediction models. The purpose of this study is to build high-accuracy and effective financial distress prediction models by two representative deep learning algorithms: Deep neural networks (DNN) …', '', '', '', '', '… This paper investigates how imitative innovation affects firms’ financial distress risk and how executive foreign experience moderates this relationship. Using the 2008–2017 patent application data for Chinese listed firms, we find robust evidence that imitative innovation …', '', '', '', '… Second, our study adds to the large body of research that analyzes factors explaining financial distress by showing that socially responsible activities matter in reducing default risk. With the focus on the probability of default with different term structure, we add a time dimension …', '']
# listSummary = ['', '', '', '', 'NS Salsabila - Polish Journal of Management Studies, 2020 - search.proquest.com', '', '', '', 'SY Phang, H Hoang - Accounting & Finance, 2021 - Wiley Online Library', 'C Jan - 2021 - search.proquest.com', '', '', '', '', 'B Liu, T Ju, M Bai, CFJ Yu - International Review of Economics & Finance, 2021 - Elsevier', '', '', '', 'TK Do - Finance Research Letters, 2021 - Elsevier', '']
# listCitedBy = ['', '', '', '', '', '', '', '', 3, '', '', '', '', '', 3, '', '', '', 1, '']
# listSource = ['', '', '', '', '', '', '', '', 'wiley', '', '', '', '', '', 'sciencedirect', '', '', '', 'sciencedirect', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=120&num=21&as_ylo=2018'
# listIndex = [0, '', 2, '', '', 5, '', '', '', '', '', 11, '', '', '', '', '', '', '', '']
# listTitle = ["Implications of the Joint Provision of CSR Assurance and Financial Audit for Auditors' Assessment of Going‐Concern Risk", '', 'How do corporate environmental policy and corporate reputation affect risk‐adjusted financial performance?', '', '', 'Corporate governance mechanisms and corporate performance of firms in Nigeria and Ghana', '', '', '', '', '', 'Is CSR reporting always favorable?', '', '', '', '', '', '', '', '']
# listLink = ['https://onlinelibrary.wiley.com/doi/abs/10.1111/1911-3846.12560', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/bse.2482', '', '', 'https://www.emerald.com/insight/content/doi/10.1108/IJPPM-01-2020-0020/full/html', '', '', '', '', '', 'https://www.emerald.com/insight/content/doi/10.1108/MD-05-2017-0540/full/html', '', '', '', '', '', '', '', '']
# listSnippet = ['… First, we use both future bankruptcies and financial distress to examine the accuracy of going-concern opinions. We compute TYPE1_BANKRUPT (TYPE2_BANKRUPT) = 1 if a firm has a going-concern opinion (clean opinion) in year t and does not fail (fails) by the end of year t …', '', '… Second, corporate reputation has a positive impact on risk-adjusted profitability and Z score indicator of financial distress risk. Thus, … From this perspective, CSR makes CR a more valuable resource than would be the case if the firm conformed less with these social norms…', '', '', '… (3) Finally, we analyze the moderating effect of financial distress on the relationship between CG and corporate performance. To do this, … This implies that financial distress affects firm’s ability in undertaking CSR activities in the society, thereby affecting the survival and growth …', '', '', '', '', '', '… They encourage further research to understand these factors and their influence on the CSR-firm performance link. During financial distress, market participants are expected to be more sensitive to financial decisions and fund allocation. The main obligation for management is …', '', '', '', '', '', '', '', '']
# listSummary = ['LD Maso, GJ Lobo, F Mazzi… - Contemporary …, 2020 - Wiley Online Library', '', 'F Gangi, LM Daniele, N Varrone - Business Strategy and the …, 2020 - Wiley Online Library', '', '', 'M Coleman, M Wu - International Journal of Productivity and …, 2020 - emerald.com', '', '', '', '', '', 'B Al-Dah, M Dah, M Jizi - Management Decision, 2018 - emerald.com', '', '', '', '', '', '', '', '']
# listCitedBy = [20, '', 37, '', '', 2, '', '', '', '', '', 30, '', '', '', '', '', '', '', '']
# listSource = ['wiley', '', 'wiley', '', '', 'emerald', '', '', '', '', '', 'emerald', '', '', '', '', '', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=140&num=21&as_ylo=2018'
# listIndex = ['', '', 2, '', 4, '', '', '', 8, '', '', '', '', '', '', '', '', '', '', '']
# listTitle = ['', '', 'Corporate social responsibility and financial profile of Spanish private hospitals', '', 'Bank power, block ownership, boards and financial distress likelihood: An investigation of Spanish listed firms', '', '', '', 'Corporate social responsibility and bankruptcy', '', '', '', '', '', '', '', '', '', '', '']
# listLink = ['', '', 'https://www.sciencedirect.com/science/article/pii/S2405844019362838', '', 'https://www.sciencedirect.com/science/article/pii/S0929119920300808', '', '', '', 'https://www.emerald.com/insight/content/doi/10.1108/SEF-01-2018-0013/full/html', '', '', '', '', '', '', '', '', '', '', '']
# listSnippet = ['', '', '… After a review of relevant academic literature and a justification of the indicators, this article presents a PLS-SEM for identifying key relationships between CSR and financial indicators, which could be considered in the agendas of private hospital institutions. …', '', '… We find a positive relationship between bank power and financial distress likelihood—that is, firms in which banks have power are more likely than their counterparts to enter financial distress. We also find evidence linking blockholder power and board independence to …', '', '', '', '… is whether CSR plays a role in determining the likelihood of bankruptcy. Does CSR make a difference in whether a firm faces the ultimate in financial distress … This paper extends the existing CSR literature but looks at CSR not from the angel of financial “success” but rather from …', '', '', '', '', '', '', '', '', '', '', '']
# listSummary = ['', '', 'J Creixans-Tenas, G Coenders, N Arimany-Serrat - Heliyon, 2019 - Elsevier', '', 'M Mangena, AM Priego, M Manzaneque - Journal of Corporate Finance, 2020 - Elsevier', '', '', '', 'E Cooper, H Uzun - Studies in Economics and Finance, 2019 - emerald.com', '', '', '', '', '', '', '', '', '', '', '']
# listCitedBy = ['', '', 18, '', 11, '', '', '', 13, '', '', '', '', '', '', '', '', '', '', '']
# listSource = ['', '', 'sciencedirect', '', 'sciencedirect', '', '', '', 'emerald', '', '', '', '', '', '', '', '', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=160&num=21&as_ylo=2018'
# listIndex = ['', '', 2, 3, '', 5, '', 7, '', '', 10, '', '', '', '', '', '', '', '', '']
# listTitle = ['', '', 'The Relationship Between Earnings Before Interest and Taxes (EBIT) and Financial Distress in the Renewable Energy Industry', 'Corporate social responsibility, financial performance and risk in Indonesian natural resources industry', '', 'Rethinking capital structure decision and corporate social responsibility in response to COVID‐19', '', 'Corporate distress prediction in China: A machine learning approach', '', '', 'Does it pay to be an honest entrepreneur? Addressing the relationship between sustainable development and bankruptcy risk', '', '', '', '', '', '', '', '', '']
# listLink = ['', '', 'https://search.proquest.com/openview/3f97b9c10e4afc7bb5b59bdcff7b8042/1?pq-origsite=gscholar&cbl=18750&diss=y', 'https://www.emerald.com/insight/content/doi/10.1108/SRJ-06-2018-0155/full/html', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/acfi.12740', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/acfi.12432', '', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/csr.1901', '', '', '', '', '', '', '', '', '']
# listSnippet = ['', '', "… Financial distress in this research referred to measuring the Altman Z score's elements, which calculates critical financial ratios for companies operating in renewable energy. The main variables of the research are outlined in the following subsections. …", '… the empirical confirmation on the correlation of corporate social responsibility (CSR), corporate financial performance (CFP) and risk. Likewise… by using CSR may add value to investors who have the tendency to be risk averse, as well as decreasing the costs of financial distress. …', '', '… In addition to firms’ stock return volatilities, we measure firm’s financial distress risk to evaluate the likelihood of being bankrupt. As COVID-19 has already resulted in many bankruptcy cases, it is crucial to examine the impact of deviation from optimal capital structure and …', '', '… better performing companies, we anticipate a negative relationship between executive compensation and firm financial distress in China. … For the purposes of this study, we use two key CSR measures from the China Stock Market and Accounting Research (CSMAR) database (i…', '', '', '… The main aim of our research has been related to the opportunity to fill the literature gap about the relationship between CSR and financial distress. Furthermore, our research has been conducted during a period characterized by a high degree of attention paid by policy makers …', '', '', '', '', '', '', '', '', '']
# listSummary = ['', '', 'E Sarpong - 2021 - search.proquest.com', 'D Devie, LP Liman, J Tarigan, F Jie - Social Responsibility Journal, 2018 - emerald.com', '', 'H Huang, Y Ye - Accounting & Finance, 2021 - Wiley Online Library', '', 'Y Jiang, S Jones - Accounting & Finance, 2018 - Wiley Online Library', '', '', 'S Pizzi, F Caputo, A Venturelli - … Social Responsibility and …, 2020 - Wiley Online Library', '', '', '', '', '', '', '', '', '']
# listCitedBy = ['', '', 1, 32, '', 3, '', 23, '', '', 7, '', '', '', '', '', '', '', '', '']
# listSource = ['', '', 'proquest', 'emerald', '', 'wiley', '', 'wiley', '', '', 'wiley', '', '', '', '', '', '', '', '', '']

# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=180&num=21&as_ylo=2018'
# listIndex = ['', '', '', '', '', 5, '', '', '', 9, '', 11, '', '', '', '', '', 17, '', '']
# listTitle = ['', '', '', '', '', 'Predicting the risk of financial distress using corporate governance measures', '', '', '', 'Human behavior analysis under financial information science: Evidence from corporate social responsibility', '', 'Corporate social responsibility and bankruptcy probability: Exploring the role of market competition, intellectual capital, and equity cost', '', '', '', '', '', 'Re-thinking the CSP–CFP Linkage: Analyzing the Mechanisms Involved in Translating Socially Responsible Behavior to Financial Performance', '', '']
# listLink = ['', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S0927538X19305542', '', '', '', 'https://www.emerald.com/insight/content/doi/10.1108/LHT-11-2016-0130/full/html', '', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/jcaf.22417', '', '', '', '', '', 'https://www.emerald.com/insight/content/doi/10.1108/S0742-332220180000038014/full/html', '', '']
# listSnippet = ['', '', '', '', '', '… In state-owned companies where the government has large concentrated shares, state ownership leads to problems of corruption and social responsibility. Therefore, state ownership is a double-edged sword: advantages and disadvantages interact to influence firm …', '', '', '', '… We argue that profitable CSR activities can increase a firm’s transparency by reducing the firm’s perceived risk of financial distress in several ways. First, CSR performance can improve the relationship between stakeholders and firm and improve a firm’s long-term sustainability. …', '', '… Due to the importance of bankruptcy, financial and accounting thinkers all over the world are looking for ways to predict corporate financial distress and bankruptcy. Logically, it is expected that firms that use CSR should be less costly than its shareholding, and CSR should …', '', '', '', '', '', '… In this chapter, we reexamine the notion that socially responsible behavior by firms will lead to increased financial performance. By … the effect of financial distress or difficulty on social responsibility was observed when at the peak of the current credit crisis, in some large financial …', '', '']
# listSummary = ['', '', '', '', '', 'Z Li, J Crook, G Andreeva, Y Tang - Pacific-Basin Finance Journal, 2021 - Elsevier', '', '', '', 'FJ Hsu, YC Chen - Library Hi Tech, 2018 - emerald.com', '', 'H Kamalirezaei, AA Anvary Rostamy… - … & Finance, 2020 - Wiley Online Library', '', '', '', '', '', 'A Mehrpouya, I Chowdhury - 2018 - emerald.com', '', '']
# listCitedBy = ['', '', '', '', '', 25, '', '', '', 1, '', 8, '', '', '', '', '', 2, '', '']
# listSource = ['', '', '', '', '', 'sciencedirect', '', '', '', 'emerald', '', 'wiley', '', '', '', '', '', 'emerald', '', '']

#endregion

#region #before 2018
# GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=0&num=21&as_yhi=2018'
# listIndex = [0, 1, 2, 3, 4, 5, '', '', 8, '', 10, '', '', 13, '', '', '', '', '', 19]
# listTitle = ['Optimization of Monetary Corporate Social Responsibility Value Added in Reducing Financial Distress in Indonesia', 'Environmental policy, environmental performance, and financial distress in China: Do top management team characteristics matter?', 'Do private equity owners increase risk of financial distress and bankruptcy?', 'Do financial constraints matter when firms engage in CSR?', "Is a firm's financial risk associated with corporate social responsibility?", "Corporate social responsibility and shareholder's value", '', '', 'Financial distress and customer-supplier relationships', '', 'Financial distress, outside directors and corporate tax aggressiveness spanning the global financial crisis: An empirical analysis', '', '', 'Corporate social responsibility engagement of financially distressed firms and their bankruptcy likelihood', '', '', '', '', '', 'Causal relationship between CSR and FB in banks']
# listLink = ['https://search.proquest.com/openview/18a85e4701c846d4fe75c3b7b36ca557/1?pq-origsite=gscholar&cbl=816338', 'https://onlinelibrary.wiley.com/doi/abs/10.1002/bse.2229', 'https://www.sciencedirect.com/science/article/pii/S0929119911001210', 'https://www.sciencedirect.com/science/article/pii/S1062940816301279', 'https://www.emerald.com/insight/content/doi/10.1108/MD-02-2015-0047/full/html', 'https://www.sciencedirect.com/science/article/pii/S0148296311003663', '', '', 'https://www.sciencedirect.com/science/article/pii/S092911991730086X', '', 'https://www.sciencedirect.com/science/article/pii/S0378426614003756', '', '', 'https://www.sciencedirect.com/science/article/pii/S0882611018300981', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S221446251730124X']
# listSnippet = ['This study tried to investigate about a form of solution model and new empirical evidence which is not only related to how the effect of the application of Corporate Social Responsibility (CSR) to improve financial performance but also the measurement of benefits …', '… In particular, the disclosure of environmental and socially responsible activities is still voluntary for Chinese firms, who strive to attain social legitimacy and efficiency within the society. Further, except independent RKS ratings (recently developed following GRI and other …', '… In this study, we investigate financial distress risks of European companies around the buyout event in the period between 2000 and 2008. In addition, we analyze whether buyout companies go bankrupt more often than comparable non-buyout companies. Our results suggest …', '… , to further investigate the liquidity-CSR linkage. We explore different dimensions including the liquidity of the firms and degree of financial distress risk. We posit that the healthier the firm, the higher the ability for and possibility of engagement in CSR. Ultimately firm inclusion in …', '… We argue that profitable CSR activities can improve a firm’s credit rating by reducing the firm’s perceived risk of financial distress in several ways. First, CSR performance can improve the relationship between the firm and its stakeholders, thus improving the firm’s long-term …', '… Finally, in our event study analysis, an observational equivalence issue related to the endogeneity problem in the relationship between CSR and corporate performance may still persist if exit from the Domini 400 coincides with a financial distress shock. In such cases, the …', '', '', "… financial health is influenced by the major customer's financial conditions. I find that a supplier's probability of financial distress is positively related to its major customer's financial distress … This relation persists up to two years after a major customer is in financial distress. Further, …", '', '… financial distress and tax aggressiveness spanning the global financial crisis (GFC) of 2008 and the impact of the interaction between board independence and firm-specific financial distress … Our results are robust to multiple measures of financial distress and tax aggressiveness…', '', '', '… This study aims to evaluate the value of corporate social responsibility (CSR, henceforth) in the context of corporate financial distress. At the crux of the study is a simple question: whether and how the bankruptcy likelihood of financially distressed firms can be reduced by their …', '', '', '', '', '', '… The present study investigates the impact of corporate social responsibility (CSR) on financial performance (FB) of Lebanese banks. Based on … having the strongest CSR environments pertain outstanding financial performance and are least likely to go through financial distress. …']
# listSummary = ['N Tristiarini, Y Setiawanta… - … Economics and Financial …, 2017 - search.proquest.com', 'Y Shahab, CG Ntim, Y Chengang… - … Strategy and the …, 2018 - Wiley Online Library', 'T Tykvová, M Borell - Journal of Corporate Finance, 2012 - Elsevier', 'CY Chan, DW Chou, HC Lo - … American Journal of Economics and Finance, 2017 - Elsevier', 'FJ Hsu, YC Chen - Management Decision, 2015 - emerald.com', 'L Becchetti, R Ciciretti, I Hasan, N Kobeissi - Journal of Business Research, 2012 - Elsevier', '', '', 'Y Lian - Journal of Corporate Finance, 2017 - Elsevier', '', 'G Richardson, R Lanis, G Taylor - Journal of Banking & Finance, 2015 - Elsevier', '', '', 'KC Lin, X Dong - Advances in accounting, 2018 - Elsevier', '', '', '', '', '', 'A Abou Fayad, R Ayoub, M Ayoub - Arab Economic and Business Journal, 2017 - Elsevier']
# listCitedBy = [7, 71, 163, 52, 77, 291, '', '', 55, '', 86, '', '', 23, '', '', '', '', '', 23]
# listSource = ['proquest', 'wiley', 'sciencedirect', 'sciencedirect', 'emerald', 'sciencedirect', '', '', 'sciencedirect', '', 'sciencedirect', '', '', 'sciencedirect', '', '', '', '', '', 'sciencedirect']

GoogleScholarUrl = 'https://scholar.google.com/scholar?q=%27csr%27+AND+%27financial+distress%27&hl=en&start=10&num=21&as_yhi=2018'
listIndex = [0, '', '', 3, '', '', '', '', '', 9, 10, 11, '', '', '', '', '', '', '', '']
listTitle = ['Financial distress, outside directors and corporate tax aggressiveness spanning the global financial crisis: An empirical analysis', '', '', 'Corporate social responsibility engagement of financially distressed firms and their bankruptcy likelihood', '', '', '', '', '', 'Causal relationship between CSR and FB in banks', 'The effects of corporate governance on financial performance and financial distress: evidence from Egypt', 'Moderating effect of capital intensity on the relationship between leverage and financial distress in the US restaurant industry', '', '', '', '', '', '', '', '']
listLink = ['https://www.sciencedirect.com/science/article/pii/S0378426614003756', '', '', 'https://www.sciencedirect.com/science/article/pii/S0882611018300981', '', '', '', '', '', 'https://www.sciencedirect.com/science/article/pii/S221446251730124X', 'https://www.emerald.com/insight/content/doi/10.1108/cg-11-2014-0140/full/html', 'https://www.sciencedirect.com/science/article/pii/S0278431910001337', '', '', '', '', '', '', '', '']
listSnippet = ['… financial distress and tax aggressiveness spanning the global financial crisis (GFC) of 2008 and the impact of the interaction between board independence and firm-specific financial distress … Our results are robust to multiple measures of financial distress and tax aggressiveness…', '', '', '… This study aims to evaluate the value of corporate social responsibility (CSR, henceforth) in the context of corporate financial distress. At the crux of the study is a simple question: whether and how the bankruptcy likelihood of financially distressed firms can be reduced by their …', '', '', '', '', '', '… The present study investigates the impact of corporate social responsibility (CSR) on financial performance (FB) of Lebanese banks. Based on … having the strongest CSR environments pertain outstanding financial performance and are least likely to go through financial distress. …', '… as a financial distress indicator, as it measures financial distress inversely. The bigger the Z-score, the smaller the risk of financial distress. … At the same time, the Altman Z-score is used as a financial distress indicator, as it measures financial distress inversely. The bigger the Z-…', "… Considering Peterson's (1994) argument that an increase in a firm's risk leads to a high probability of financial distress, this study hypothesizes that a restaurant's greater leverage increases financial distress. Concerning the effect of capital intensity on financial distress, the …", '', '', '', '', '', '', '', '']
listSummary = ['G Richardson, R Lanis, G Taylor - Journal of Banking & Finance, 2015 - Elsevier', '', '', 'KC Lin, X Dong - Advances in accounting, 2018 - Elsevier', '', '', '', '', '', 'A Abou Fayad, R Ayoub, M Ayoub - Arab Economic and Business Journal, 2017 - Elsevier', 'TM Shahwan - Corporate Governance, 2015 - emerald.com', 'S Lee, Y Koh, KH Kang - International Journal of Hospitality Management, 2011 - Elsevier', '', '', '', '', '', '', '', '']
listCitedBy = [86, '', '', 23, '', '', '', '', '', 23, 209, 71, '', '', '', '', '', '', '', '']
listSource = ['sciencedirect', '', '', 'sciencedirect', '', '', '', '', '', 'sciencedirect', 'emerald', 'sciencedirect', '', '', '', '', '', '', '', '']

#endregion after 2018

# collectJurnalMainFunction()
def printListResult(index):
    print('listIndex = ',listIndex[index])
    print('listTitle = ',listTitle[index])
    print('listLink = ',listLink[index])
    print('listSnippet = ',listSnippet[index])
    print('listSummary = ',listSummary[index])
    print('listCitedBy = ',listCitedBy[index])
    print('listSource = ',listSource[index])
printListResult(11)